[package]
name = "wort"
version = "0.1.0"
authors = ["Viktor Kunovski <viktor@kunovski.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
num = "0.3"
rand = "0.8.0"
rayon = "1.5.0"
strum = "0.20"
strum_macros = "0.20"
